name: ai_chatgpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
